### ISSUE TITLE
macOS compilation instructions are outdated

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/stembuild#18]
In go1.18, `go get` can no longer be used to download repos/packages in the GOPATH.

**Comment by beyhan** [comment]
@ctlong do you plan to open a pr for this?

**Comment by ctlong** [comment]
@beyhan I've made a PR to resolve this issue: #20.

I've tested my own steps and saw that `make build` succeeded. Are there any additional tests I should run on the compiled output to ensure these new steps work?
