### ISSUE TITLE
Getting error running Set-MpPreference -

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/stembuild#21]
Getting the following error in the script when running stembuild construct.  The script continues and appears to finish correctly so I'm not sure if this is critical:

    Set-MpPreference : Operation failed with the following error: 0x%1!x!
    At line:1 char:1
    + Set-MpPreference -DisableTamperProtection $true
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Set-MpPreference],
       CimException
        + FullyQualifiedErrorId : HRESULT 0x80004001,Set-MpPreference

**Comment by rkoster** [comment]
It looks like it is coming from this code: https://github.com/cloudfoundry/stembuild/blob/9da36741b7c800d24313914689dbe1127fdfa555/modules/BOSH.CFCell/BOSH.CFCell.psm1#L121-L137

It explicitly silently ignores errors. However in your case it looks like Set-MpPreference is there and only the `-DisableTamperProtection` flag does not work. Could you check what the right way for your windows is to disable tamper protection?

**Comment by rkoster** [comment]
Also which version of windows are you using?

**Comment by amhuber** [comment]
We're using Windows Server 2019, created using the process documented at https://bosh.io/docs/windows-stemcell-create/.  I can confirm that all the "disable" commands work other than DisableTamperProtection.  If I just run that command on a provisioned cell I get the same error:

    PS C:\Users\Administrator> Set-MpPreference -DisableTamperProtection $true
    Set-MpPreference : Operation failed with the following error: 0x%1!x!
    At line:1 char:1
    + Set-MpPreference -DisableTamperProtection $true
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Set-MpPreference],
       CimException
        + FullyQualifiedErrorId : HRESULT 0x80004001,Set-MpPreference

If I run Get-MpPreference there are no preferences listed related to tamper protection.  I can't find any Microsoft documentation that the DisableTamperProtection command exists or is supported, and most articles related to disabling tamper protection indicate that you have to modify the setting in the UI or via Group Policy.

In any case, it does appear that Defender is actually off in our stemcells, so I'm OK with just ignoring the error when we create the stemcell.  My guess is that Microsoft added the DisableTamperProtection function in PowerShell but it's not supported yet.  Maybe it will be supported on Windows 2022 for example.

If you aren't able to reproduce the error feel free to close this issue as I don't think there is any actual problem since the error is ignored and the build continues successfully.  Thanks for investigating.

**Comment by rkoster** [comment]
Thanks for the follow up! Yeah, it seems safe to ingore.
